apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  rules: {{ $releaseName := .Release.Name }}{{ range $host := .Values.expose.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: 5000
  {{ end }}