name: test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: setup k3s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
          kubectl version
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml

      - run: make cover
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml

      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
          flags: unittests